version: '2.4'
services:
  kafka:
    image: landoop/fast-data-dev
    ports:
      - "2181:2181"
      - "3030:3030"
      - "3031:3031"
      - "9092:9092"
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
    container_name: kafka
    environment:
      - ADV_HOST=127.0.0.1

  wiremock:
    image: rodolpheche/wiremock
    ports:
      - 8151:8080
    container_name: wiremock

